name: Deploy to AKS from ACR

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
   # steps:
 #   - name: Checkout code
 #     uses: actions/checkout@v2
 #   - name: Set up Azure CLI
 #     uses: azure/login@v1
 #     with:
 #       creds: ${{ secrets.AZURE_CREDENTIALS }}
 #   - name: Login to Azure Container Registry
 #     uses: azure/docker-login@v1
  #    with:
  #      login-server: test0107.azurecr.io
   #     username: ${{ secrets.ACR_USERNAME }}
   #     password: ${{ secrets.ACR_PASSWORD }}
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Generate Image Tag
      id: generate_tag
      run: echo "::set-output name=image_tag::$(git rev-parse --short HEAD)"

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    
    - name: Build Docker image
      run: | 
       # docker build -t test0107.azurecr.io/asg:${{ github.sha }} .
       # docker push test0107.azurecr.io/asg:${{ github.sha }}
       docker build -t asg:${{ steps.generate_tag.outputs.image_tag }} .
        docker tag asg:${{ steps.generate_tag.outputs.image_tag }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/asg:${{ steps.generate_tag.outputs.image_tag }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/asg:${{ steps.generate_tag.outputs.image_tag }}

    - name: Get Latest Image Tag from ACR
      id: get_image_tag
      run: |
        TAG=$(az acr repository show-tags --name test0107 --repository asg --orderby time_desc --top 1 --output tsv)
        echo "::set-output name=image_tag::$TAG"

    - name: Update deployment.yaml
      run: |
        sed -i'' "s|image:[^:]*$|image: test0107.azurecr.io/asg:${{ steps.get_image_tag.outputs.image_tag }}|g" deployment.yaml
